/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chat4me.util;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        CompletionClient classUnderTest = new CompletionClient();
        assertNotNull(classUnderTest.sendCompletionRequest());
    }
}
